### ISSUE TITLE
Silent Data truncation with GDAL 2.x

### ISSUE THREAD

**Issue by bhaskarvk** [walkerke/tigris#21]
GDal 2.x introduced int64, which R doesn't support (as of yet).
`rgdal::readOGR` changes the way it interprets numeric fields with values outside int32 range ( outside -2^32 to +2^31). with Gdal 1.x as there was no int64 the fields were interpreted as Real and converted to numeric, but if Gdal 2.x, any numeric field beyond int32 is handled using the 'interger64' argument of readOGR.

The current default is 'allow.loss' which silently truncates anything outside int32 range. This means the ALAND, AWATER fields of most shapefiles have truncated data.

https://gist.github.com/bhaskarvk/686deca51e3e81cb785ed8f2430ac2fc

Proposed workaround:-
Add `integer64='no.loss'` to the readOGR call, and then convert the chars for these fields to numeric. I doubt any of these fields will have AREA > 2^53 (MAX double), so the char to numeric (double) conversion should not result in any loss of data.

rgdal will probably be changed to make 'no.loss' the default option at some point in time, but for now this is a pressing issue especially for anyone using the ALAND/AWATER or for that matter any numeric field with values beyond the int32 range .

**Comment by walkerke** [comment]
Thanks for the catch!  I'll take a look at this.

**Comment by edzer** [comment]
`integer64='no.loss'` has become the default in current `rgdal::readOGR`.

In `sf::st_read` however, it might be useful to set `int64_as_string = TRUE` in order to avoid such a loss, or at least allow the user to pass this on to `st_read`. `st_read` currently converts these to double, and issues a warning when information is lost, i.e. integers larger than 2^53 are encountered.

As discussed elsewhere, it is somewhat tricky to sort out what is the right thing to do: in principle, it is not a good idea to encode identifiers as integer numbers, character would be more appropriate.
