### ISSUE TITLE
Availability of commuting zones in tigris?

### ISSUE THREAD

**Issue by davidkane9** [walkerke/tigris#53]
I use tigris with my class. The zctas functions works wonderfully. But now we want to work with commuting zones.

1) I do not see commuting zones as available in tigris. Am I missing something?

2) I see commuting zone information in your US Boundaries package. However, I can't even load the data there into R. Any advice?

Thanks!

**Comment by walkerke** [comment]
Hi David,

It doesn't look like commuting zones have been defined since 2000, which is why they are not in the current TIGER/Line shapefile products (and as such not in tigris).  The USDA ERS maintains crosswalk files for historic commuting zones, you could use these to map counties to zones: https://www.ers.usda.gov/data-products/commuting-zones-and-labor-market-areas/
